spring:
  datasource:
    username: ''
    password: ''
    driver-class-name: org.postgresql.Driver
    url: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false


